### ISSUE TITLE
Add information about licensing

### ISSUE THREAD

**Issue by vbauer** [lucastan/android-icon-copier#1]
It would be also great to add information about licensing.

PS: Project was added on the Android Arsenal. If you would like to support AA, you could add this badge in the README file (I will really appreciate it):

```
[![Android Arsenal](https://img.shields.io/badge/Android%20Arsenal-android--icon--copier-brightgreen.svg?style=flat)](https://android-arsenal.com/details/1/1325)
```

**Comment by lucastan** [comment]
All done! thanks!
