### ISSUE TITLE
missing res dir

### ISSUE THREAD

**Issue by bzkdjc** [lucastan/android-icon-copier#2]
Command just logs:
```
missing res dir
```
as only output and exits!

On Ubuntu 14.04.3. Using Android.

Wanted to get all dp of _content copy_ from category Content of GMD icons...
Tried so far:
* `./copy ../proj content blue content_copy`
* `./copy /home/me/projects/project1/app content blue content_copy` 
* `./copy /home/me/projects/project1/app/src/main/res content blue content_copy` 
* `./copy "/home/me/projects/project1/app/src/main/res content" blue content_copy` 
* `./copy "/home/me/projects/project1/app/" blue content_copy` 

Still I get that same message!

**Comment by lucastan** [comment]
The 'res' paths it will try are:
[base_path]/[proj]/src/main/res
[base_path]/[proj]/res

where [base_path] is in the options file, [proj] is the project path as per what you typed in.

please ensure these are correct
